classes:
- system.cassandra.backup.client.single
parameters:
  _param:
    root_private_key: |
      <<WILL_BE_GENERATED>>
  cassandra:
    backup:
      client:
        target:
          backup_dir: /srv/volumes/backup/cassandra
