classes:
- system.linux.system.repo.mcp.salt
- system.linux.system.repo.mcp.extra
- system.linux.system.repo.mcp.apt_mirantis.openstack
- system.linux.system.repo.mcp.apt_mirantis.ubuntu
- system.linux.system.repo.mcp.apt_mirantis.glusterfs
- system.linux.system.repo.mcp.apt_mirantis.saltstack
- system.glusterfs.client.cluster
- system.glusterfs.client.volume.salt_pki
- system.salt.master.pkg
- system.salt.master.formula.pkg.manila
- system.salt.master.formula.pkg.gnocchi
- system.salt.master.formula.pkg.panko
- system.salt.minion.ca.salt_master
- system.salt.master.api
- system.reclass.storage.salt
- system.reclass.storage.system.physical_control_cluster
- system.reclass.storage.system.openstack_gateway_cluster
- system.reclass.storage.system.openstack_control_cluster
- system.reclass.storage.system.openstack_proxy_cluster
- system.reclass.storage.system.openstack_database_cluster
- system.reclass.storage.system.openstack_message_queue_cluster
- system.reclass.storage.system.openstack_telemetry_cluster
- service.jenkins.client
- system.jenkins.client.credential.salt
- system.jenkins.client.job.deploy.openstack
- cluster.jenkins-oscore-test-cookiecutter-model-423.infra
- cluster.jenkins-oscore-test-cookiecutter-model-423.infra.backup.client_common
- cluster.jenkins-oscore-test-cookiecutter-model-423.infra.networking.config
- cluster.jenkins-oscore-test-cookiecutter-model-423.infra.validate
parameters:
  _param:
    deploy_address: ${_param:infra_config_deploy_address}
    http_proxy: ''
    http_proxy_address: ''
    http_proxy_port: ''
    jenkins_gerrit_url: ${_param:jenkins_git_url}
    jenkins_git_url: git@cfg01:/home/repo
    jenkins_pipeline_library_url: git@cfg01:/home/repo/mcp-ci/pipeline-library
    jenkins_salt_api_url: http://${_param:salt_master_host}:6969
    linux_system_codename: xenial
    reclass_config_master: ${_param:infra_config_deploy_address}
    reclass_data_repository: https://github.com/Mirantis/mk-lab-salt-model.git
    reclass_data_revision: master
    salt_api_password: hovno12345!
    salt_api_password_hash: $6$sGnRlxGf$al5jMCetLP.vfI/fTl3Z0N7Za1aeiexL487jAtyRABVfT3NlwZxQGVhO7S1N8OwS/34VHYwZQA8lkXwKMN/GS1
    salt_master_base_environment: prd
    salt_master_host: ${_param:infra_config_deploy_address}
    single_address: ${_param:infra_config_address}
  jenkins:
    client:
      lib:
        pipeline-library:
          branch: ${_param:jenkins_pipelines_branch}
          url: ${_param:jenkins_pipeline_library_url}
      master:
        host: ${_param:salt_master_host}
        password: r00tme
        port: 8081
  reclass:
    storage:
      data_source:
        engine: local
      node:
        infra_kvm_node01:
          classes:
          - cluster.jenkins-oscore-test-cookiecutter-model-423.infra.glusterfs
          params:
            keepalived_vip_priority: 100
            linux_system_codename: xenial
        infra_kvm_node02:
          classes:
          - cluster.jenkins-oscore-test-cookiecutter-model-423.infra.glusterfs
          params:
            keepalived_vip_priority: 101
            linux_system_codename: xenial
        infra_kvm_node03:
          classes:
          - cluster.${_param:cluster_name}.infra.backup.server
          - cluster.jenkins-oscore-test-cookiecutter-model-423.infra.glusterfs
          params:
            keepalived_vip_priority: 102
            linux_system_codename: xenial
        openstack_compute_rack01:
          classes:
          - cluster.${_param:cluster_name}.openstack.compute
          domain: ${_param:cluster_domain}
          name: ${_param:openstack_compute_rack01_hostname}<<count>>
          params:
            linux_system_codename: xenial
            salt_master_host: ${_param:reclass_config_master}
          repeat:
            count: 2
            digits: 0
            params:
              single_address:
                start: 101
                value: ${_param:openstack_compute_rack01_single_subnet}.<<count>>
              tenant_address:
                start: 101
                value: ${_param:openstack_compute_rack01_tenant_subnet}.<<count>>
            start: 1
        openstack_control_node01:
          classes:
          - cluster.${_param:cluster_name}.openstack.control_init
          params:
            linux_system_codename: xenial
        openstack_control_node02:
          params:
            linux_system_codename: xenial
        openstack_control_node03:
          params:
            linux_system_codename: xenial
        openstack_database_node01:
          classes:
          - cluster.${_param:cluster_name}.openstack.database_init
          params:
            linux_system_codename: xenial
        openstack_database_node02:
          params:
            linux_system_codename: xenial
        openstack_database_node03:
          params:
            linux_system_codename: xenial
        openstack_message_queue_node01:
          params:
            linux_system_codename: xenial
        openstack_message_queue_node02:
          params:
            linux_system_codename: xenial
        openstack_message_queue_node03:
          params:
            linux_system_codename: xenial
        openstack_proxy_node01:
          params:
            linux_system_codename: xenial
        openstack_proxy_node02:
          params:
            linux_system_codename: xenial
        openstack_telemetry_node01:
          params:
            linux_system_codename: xenial
            ceilometer_create_gnocchi_resources: true
            redis_cluster_role: 'master'
        openstack_telemetry_node02:
          params:
            linux_system_codename: xenial
            redis_cluster_role: 'slave'
        openstack_telemetry_node03:
          params:
            linux_system_codename: xenial
            redis_cluster_role: 'slave'
  salt:
    master:
      backup: true
      command_timeout: 600
      reactor:
        reclass/minion/classify:
        - salt://reclass/reactor/node_register.sls
      user:
        deploy:
          permissions: ${_param:salt_master_api_permissions}
    minion:
      backup: true
